apiVersion: v1
kind: Pod
metadata:
  name: nginx-disallowed
  labels:
    app: nginx-disallowed
spec:
  automountServiceAccountToken: true
  hostPID: true
  hostIPC: true
  securityContext:
    runAsUser: 1
    fsGroup: 1
    runAsGroup: 1
    supplementalGroups: [1]
    sysctls:
    - name: kernel.msgmax
      value: "65536"
  containers:
  - name: nginx-disallowed
    image: nginx
    resources:
      limits:
        cpu: "500m"
        memory: "2Gi"
    ports:
    - containerPort: 9001
      hostPort: 9001
    securityContext:
      privileged: true
      procMount: Unmasked
      readOnlyRootFilesystem: false
      allowPrivilegeEscalation: true
      capabilities:
        add: ["CAP_SYS_ADMIN"]
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
      readOnly: true
  volumes:
  - name: cache-volume
    hostPath:
      path: /tmp # directory location on host
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-disallowed
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007